# Generated by Django 2.1 on 2019-01-08 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=200)),
                ('languages', models.TextField(blank=True, null=True)),
                ('repository_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='repodetails',
            name='usernames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.usernames'),
        ),
    ]
